name       : m64py
version    : 0.2.4
release    : 2
source     :
    - https://github.com/mupen64plus/mupen64plus-ui-python/archive/0.2.4.tar.gz : e233e0356ecc1e60bf615808547b8b79b458b49174f0f9d4089b48ad1b49a02f
license    :
    - BSD-3-Clause     #loader.py
    - CC-BY-SA-3.0     #Mupen64plus logo, Python snake logo, Controller image
    - GPL-2.0-or-later #joystick.py
    - GPL-3.0-or-later #m64py
    - Public Domain    #Icons
component  : games.emulator
summary    : Qt5 front-end for Mupen64Plus
description: |
    M64Py is a Qt5 front-end (GUI) for Mupen64Plus, a cross-platform plugin-based Nintendo 64 emulator. Front-end is written in Python and it provides a user-friendly interface over the Mupen64Plus shared library.
builddeps  :
    - python-qtpy
    - python-sdl2
rundeps    :
    - mupen64plus
    - python-qtpy
    - python-sdl2
build      : |
    %python3_setup
install    : |
    %python3_install
