name       : m64py
version    : 0.2.5
release    : 9
source     :
    - git|https://github.com/mupen64plus/mupen64plus-ui-python.git : 2c27f94f4dd25916bdce6ad981721dd751b9d739
license    :
    - BSD-3-Clause     #loader.py
    - CC-BY-SA-3.0     #Mupen64plus logo, Python snake logo, Controller image
    - GPL-2.0-or-later #joystick.py
    - GPL-3.0-or-later #m64py
    - Public Domain    #Icons
component  : games.emulator
summary    : Qt5 front-end for Mupen64Plus
description: |
    M64Py is a Qt5 frontend (GUI) for Mupen64Plus, a cross-platform plugin-based Nintendo 64 emulator. The frontend is written in Python and it provides a user-friendly interface over the Mupen64Plus shared library.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - python-qtpy
    - python-sdl2
    - python3-qt5
rundeps    :
    - mupen64plus
    - python-qtpy
    - python-sdl2
build      : |
    %python3_setup
install    : |
    %python3_install
